import test from 'node:test';
import assert from 'node:assert/strict';
const api = await import('../engine.mjs').catch(() => ({}));
const polynomial = () => ({headers:['a','b','y'], rows:Array.from({length:160},(_,i)=>{const a=-2+4*i/159,b=((i*37)%157)/31;return [a,b,1.7+2.4*a*a+0.8*b];})});
const options = {seed:42, family:'algebra', maxTerms:3};
const run = () => api.discover(polynomial(), options);
test('CSV accepts BOM, CRLF, quotes and decimal exponent',()=>assert.deepEqual(api.parseCSV('\ufeff"x",y\r\n1e-2,3\r\n2,4\r\n').rows,[[.01,3],[2,4]]));
test('CSV rejects duplicate headers',()=>assert.throws(()=>api.parseCSV('x,x\n1,2'),/header/i));
test('CSV rejects formula injection as numeric data',()=>assert.throws(()=>api.parseCSV('x,y\n=alert(1),2'),/numeric|number/i));
test('CSV rejects missing values',()=>assert.throws(()=>api.parseCSV('x,y\n1,'),/missing|numeric|number/i));
test('CSV rejects Infinity and NaN',()=>{for(const s of ['Infinity','NaN','1e999'])assert.throws(()=>api.parseCSV(`x,y\n1,${s}`),/finite|numeric|number/i);});
test('CSV rejects inconsistent width',()=>assert.throws(()=>api.parseCSV('x,y\n1,2,3'),/column|width/i));
test('CSV rejects unclosed quotes',()=>assert.throws(()=>api.parseCSV('x,y\n"1,2'),/quote/i));
test('CSV rejects unsafe and excessively long headers',()=>assert.throws(()=>api.parseCSV('<img>,y\n1,2'),/header/i));
test('CSV rejects too many inputs',()=>assert.throws(()=>api.parseCSV('a,b,c,d,e,y\n1,2,3,4,5,6'),/input|column/i));
test('CSV rejects oversized input',()=>assert.throws(()=>api.parseCSV('x'.repeat(1048577)),/MiB|size|large/i));
test('CSV rejects hexadecimal rather than coercing it',()=>assert.throws(()=>api.parseCSV('x,y\n0x10,2'),/numeric|number/i));
test('CSV rejects extreme numeric magnitude',()=>assert.throws(()=>api.parseCSV('x,y\n1000001,2'),/magnitude|range/i));
test('split is deterministic and covers every row once',()=>{const d=polynomial(),a=api.splitData(d,42),b=api.splitData(d,42);assert.deepEqual(a,b);const all=[...a.train,...a.validation,...a.test];assert.equal(new Set(all).size,d.rows.length);assert.equal(all.length,d.rows.length);});
test('duplicate input groups never leak across splits',()=>{const d=polynomial();d.rows.push([...d.rows[0]]);const s=api.splitData(d,42);assert.ok(Object.values(s).filter(Array.isArray).some(v=>v.includes(0)&&v.includes(160)));});
test('ordered split preserves unique-group order',()=>{const s=api.splitData(polynomial(),42,'ordered');assert.equal(s.train[0],0);assert.ok(Math.max(...s.train)<Math.min(...s.validation));assert.ok(Math.max(...s.validation)<Math.min(...s.test));});
test('insufficient independent data is rejected',()=>assert.throws(()=>api.discover({headers:['x','y'],rows:Array.from({length:40},()=>[1,2])},options),/distinct|independent|unique/i));
test('polynomial law is recovered on held-out rows',()=>{const r=run();assert.ok(r.test.rmse<1e-8,JSON.stringify(r.champion));assert.ok(r.test.r2>0.999999);assert.ok(r.champion.expression.includes('a^2'));});
test('recovered model predicts an unseen point',()=>assert.ok(Math.abs(api.predict(run().champion,[1.23,2.31])-(1.7+2.4*1.23**2+0.8*2.31))<1e-8));
test('final-target poisoning cannot change model selection or proposed experiment',()=>{const d=polynomial(),s=api.splitData(d,42),r=api.discover(d,options);const changed=structuredClone(d);for(const i of s.test)changed.rows[i][2]+=500;const other=api.discover(changed,options);assert.deepEqual(other.champion,r.champion);assert.deepEqual(other.experiment,r.experiment);assert.ok(other.test.rmse>400);});
test('constant target produces finite output and undefined R squared',()=>{const d=polynomial();d.rows=d.rows.map(r=>[r[0],r[1],7]);const r=api.discover(d,options);assert.equal(r.test.r2,null);assert.ok(r.test.rmse<1e-10);assert.equal(r.status,'constant_target');});
test('collinear inputs do not crash and trigger a warning',()=>{const d={headers:['a','b','y'],rows:Array.from({length:120},(_,i)=>[i/30,i/30,3*i/30+2])};const r=api.discover(d,options);assert.ok(r.test.rmse<1e-8);assert.ok(r.warnings.some(w=>/correlat/i.test(w)));assert.ok(r.experiment&&r.experiment.disagreement>0.1);});
test('experiment stays inside coordinate ranges and is not an observed point',()=>{const d=polynomial(),r=api.discover(d,options);if(r.experiment){r.experiment.inputs.forEach((x,j)=>{assert.ok(x>=Math.min(...d.rows.map(v=>v[j])));assert.ok(x<=Math.max(...d.rows.map(v=>v[j])));});assert.ok(!d.rows.some(v=>v.slice(0,-1).every((x,j)=>x===r.experiment.inputs[j])));}});
test('fixed random noise is not called supported generalization',()=>{let s=91;const rnd=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};const d={headers:['x','y'],rows:Array.from({length:300},()=>[rnd(),rnd()])};const r=api.discover(d,options);assert.equal(r.status,'not_supported');});
test('search has an explicit bounded evaluation count',()=>{const r=run();assert.ok(r.search.evaluated>0&&r.search.evaluated<=1500);});
test('repeated runs reproduce all mathematical outputs',()=>assert.deepEqual(run(),run()));
test('invalid options cannot create unbounded search',()=>{for(const o of [{maxTerms:99},{seed:NaN},{family:'eval'},{mode:'unknown'}])assert.throws(()=>api.discover(polynomial(),o),/option|seed|term|family|mode/i);});
test('structured API validates dimensions and finite values',()=>{const d=polynomial();d.rows[0][0]=NaN;assert.throws(()=>api.discover(d,options),/finite|numeric|number/i);});
test('expanded grammar recovers a sinusoidal relation',()=>{const d={headers:['x','y'],rows:Array.from({length:160},(_,i)=>{const x=-3+6*i/159;return [x,1.5+2*Math.sin(x)];})};const r=api.discover(d,{...options,family:'expanded'});assert.ok(r.test.rmse<1e-8,r.champion.expression);});
test('all synthetic examples declare their origin',()=>{for(const k of ['polynomial','confounded','noise']){const d=api.makeDemo(k);assert.equal(d.origin,'synthetic');assert.ok(d.rows.length>=100);}});
test('unknown synthetic scenario is rejected',()=>assert.throws(()=>api.makeDemo('invented'),/demo|scenario/i));
test('all-empty data records are rejected rather than silently discarded',()=>assert.throws(()=>api.parseCSV('x,y\n1,2\n,\n3,4'),/missing|numeric|number/i));
test('prediction rejects wrong input dimensionality',()=>assert.throws(()=>api.predict(run().champion,[1]),/input|dimension/i));
test('CLI produces the same selected model as browser core',async()=>{const {execFileSync}=await import('node:child_process');const {mkdtempSync,writeFileSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const {join}=await import('node:path');const dir=mkdtempSync(join(tmpdir(),'discovery-test-'));try{const file=join(dir,'data.csv');writeFileSync(file,api.toCSV(polynomial()));const output=JSON.parse(execFileSync(process.execPath,['cli.mjs',file],{encoding:'utf8'}));assert.deepEqual(output.result.champion,run().champion);assert.equal(output.datasetSHA256.length,64);}finally{rmSync(dir,{recursive:true});}});
test('an undefined reciprocal on final inputs is an explicit failed result',()=>{const d={headers:['x','y'],rows:Array.from({length:100},(_,i)=>{const x=i===99?0:1+i/20;return [x,x===0?0:1/x];})};const r=api.discover(d,{...options,mode:'ordered'});assert.equal(r.status,'invalid_on_holdout');assert.equal(r.test.invalid,true);});
test('NIST reference example retains observed-data provenance',()=>{const d=api.makeDemo('nist');assert.equal(d.origin,'observed-reference');assert.equal(d.rows.length,36);assert.match(d.truth,/NIST/);});
